'use client';
import { useEffect,useRef,useState, type FormEvent } from 'react';
import { Mountain,Plus,Users,Menu,X,Download,CheckCircle2 } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import LeaderDesk from './leader-desk';
import SummitPass from './summit-pass';
import SummitExperience from './summit-experience';
import ExpeditionConsole from './expedition-console';
import ForestStory from './forest-story';
import './forest-continuity.css';
import { adventures } from '@/lib/adventures';
type State={signedIn:boolean;leader:boolean;events:{id:string;title:string;starts_at:string;location:string;details:string;status:string}[];rsvps:{event_id:string}[];member:null|{name:string;grade:string;interest:string;created_at:string};votes:{adventure_id:string;count:number}[];myVotes:{adventure_id:string}[];proposals:{id:string;title:string;category:string;description:string}[]};
async function basecampRequest<T>(init?:RequestInit):Promise<T>{
 let response:Response;
 try{response=await fetch('/api/basecamp',{...init,signal:AbortSignal.timeout(15000)});}catch{throw new Error('Could not reach basecamp. Please check your connection and try again.');}
 const data=await response.json().catch(()=>null) as (T&{error?:string})|null;
 if(!response.ok||!data)throw new Error(data?.error||'Basecamp is temporarily unavailable. Please try again.');
 return data;
}
const values=[['S','Serve your community','Use our time and abilities to make a positive difference.'],['U','Unplug and get outside','Step away from screens and experience more of the world around us.'],['M','Move beyond your comfort zone','Try something new, challenge yourself, and grow.'],['M','Make an impact','Leave our school, community, and outdoor spaces better than we found them.'],['I','Inspire others','Bring people together and encourage others to participate.'],['T','Take the lead','Develop the confidence to contribute ideas, organize, serve, and lead.']];
const peaks=[['P','Push your limits','Challenge yourself physically, personally, and as a leader.'],['E','Explore what’s out there','Experience new places, activities, people, and perspectives.'],['A','Act with service','Look for opportunities to help rather than waiting to be asked.'],['K','Keep climbing','Continue growing, learning, and moving forward.']];
export default function Summit(){
const [leaderOpen,setLeaderOpen]=useState(false);
const [arrived,setArrived]=useState(false);
const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
const [selected,setSelected]=useState(0),[modal,setModal]=useState<'join'|'idea'|'trip'|null>(null),[menu,setMenu]=useState(false),[state,setState]=useState<State|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[grade,setGrade]=useState(''),[interest,setInterest]=useState('All of it'),[category,setCategory]=useState('Explore'),[consent,setConsent]=useState(false),[packed,setPacked]=useState<string[]>([]);
const headerRef=useRef<HTMLElement>(null);
const restoredInitialHash=useRef(false);
const requestId=useRef('');const trip=adventures[selected];
async function refresh(){setLoading(true);try{const data=await basecampRequest<State>();setState(data);setLoadError('');return data;}catch(e){setLoadError(e instanceof Error?e.message:'Could not load basecamp. Please try again.');throw e;}finally{setLoading(false);}}
function retryBasecamp(){setError('');void refresh().catch(()=>undefined);}
// Restore device-only checklist after hydration; server output must stay deterministic.
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{void refresh().catch(()=>undefined);try{const saved:unknown=JSON.parse(localStorage.getItem('summit-pack')||'[]');if(Array.isArray(saved))setPacked(saved.filter((item):item is string=>typeof item==='string'));}catch{}},[]);
useEffect(()=>{
 if(!state||restoredInitialHash.current)return;
 restoredInitialHash.current=true;
 const hash=location.hash;
 if(!['#expeditions','#board','#club'].includes(hash))return;
 // Saved events and ideas can shift a deep link after the first render.
 const frame=requestAnimationFrame(()=>document.getElementById(hash.slice(1))?.scrollIntoView({behavior:'instant'}));
 return()=>cancelAnimationFrame(frame);
},[state]);
useEffect(()=>{
 const header=headerRef.current;if(!header)return;
 const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){header.querySelectorAll('nav a').forEach(link=>{if(link.getAttribute('href')==='#'+entry.target.id)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});}}},{rootMargin:'-15% 0px -55% 0px',threshold:0});
 ['basecamp','expeditions','board','club'].forEach(id=>{const el=document.getElementById(id);if(el)observer.observe(el);});return()=>observer.disconnect();
},[]);
function enterClub(e:React.MouseEvent<HTMLAnchorElement>){e.preventDefault();window.dispatchEvent(new Event('summit:enter'));}
useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice]);
function open(which:'join'|'idea'|'trip'){setError('');setModal(which);if(which==='idea')requestId.current=crypto.randomUUID();}
async function mutate(body:Record<string,unknown>,key:string){setBusy(key);setError('');try{await basecampRequest({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await refresh().catch(()=>undefined);return true;}catch(e){setError(e instanceof Error?e.message:'Could not save. Try again.');return false;}finally{setBusy('');}}
async function vote(id:string){if(!state?.signedIn){open('join');return;}const voted=state.myVotes.some(v=>v.adventure_id===id);if(await mutate({action:'vote',adventureId:id,selected:!voted},id))setNotice(voted?'Vote removed.':'Vote saved. Your crew helps choose what’s next.');}
async function rsvp(id:string){if(!state?.member){open('join');return;}const saved=state.rsvps.some(r=>r.event_id===id);if(await mutate({action:'rsvp',eventId:id,selected:!saved},id))setNotice(saved?'RSVP removed.':'RSVP saved. Check event details and required permissions.');}
async function join(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({action:'join',name:f.get('name'),grade,interest,consent},'join'))setNotice('Your club interest is saved. Welcome to basecamp.');}
async function propose(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({action:'propose',title:f.get('title'),description:f.get('description'),category,requestId:requestId.current},'idea')){setModal(null);setNotice('Idea saved to your basecamp and the leadership desk.');}}
function pack(item:string){const next=packed.includes(item)?packed.filter(x=>x!==item):[...packed,item];setPacked(next);try{localStorage.setItem('summit-pack',JSON.stringify(next));}catch{setNotice('Checklist updated for this visit. This browser could not save it for next time.');}}
function downloadPlan(){const blob=new Blob([`SUMMIT FIELD NOTES\n${trip.name}\n${trip.place}\n\nPROPOSED EXPERIENCE — NOT A SCHEDULED EVENT\n${trip.description}\n\nPACK LIST\n${trip.bring.map(x=>`${packed.includes(x)?'[x]':'[ ]'} ${x}`).join('\n')}\n\n${trip.note}\n\nFounder & President: Tobias Kell\nCathedral Catholic High School\nExplore. Serve. Lead.`],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`summit-${trip.id}-field-notes.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const connectionPrompt=<div className="auth-prompt"><p role={loadError?'alert':'status'}>{loading?'Connecting to basecamp…':loadError||'Connect to basecamp to continue.'}</p><button className="button" disabled={loading} onClick={retryBasecamp}>{loading?'Connecting…':'Try again'}</button></div>;
return <><a className="skip" href="#basecamp" onClick={enterClub}>Skip to club basecamp</a><header ref={headerRef} className="masthead journey-nav" data-arrived={arrived}><a href="#home" className="wordmark"><Mountain size={30} strokeWidth={2.3}/><b>SUMMIT</b><span>CATHEDRAL CATHOLIC<br/>OUTDOOR CLUB</span></a><nav className={menu?'open':''}><a onClick={e=>{setMenu(false);enterClub(e)}} href="#basecamp">The club</a><a onClick={()=>setMenu(false)} href="#expeditions">What’s next</a><a onClick={()=>setMenu(false)} href="#board">Your ideas</a></nav><button className="join-nav" onClick={()=>open('join')}>{state?.member?'My club pass':'Join SUMMIT'}<Plus size={17}/></button><button className="mobile-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main><SummitExperience onJoin={()=>open('join')} onReveal={setArrived}><ForestStory onJoin={()=>open('join')}/></SummitExperience><section className="camp-calendar section">{!!state?.events?.length&&<div className="upcoming-events"><div className="section-heading"><h3>On the calendar.</h3><p>Confirmed by club leadership · Times shown in Pacific</p></div>{state.events.map(event=><article className="event-card" key={event.id}><div className="event-date"><span>{new Date(event.starts_at).toLocaleDateString('en-US',{timeZone:'America/Los_Angeles',month:'short'})}</span><strong>{new Date(event.starts_at).toLocaleDateString('en-US',{timeZone:'America/Los_Angeles',day:'numeric'})}</strong></div><div><h3>{event.title}</h3><span>{new Date(event.starts_at).toLocaleTimeString('en-US',{timeZone:'America/Los_Angeles',hour:'numeric',minute:'2-digit'})} Pacific · {event.location}</span><p>{event.details}</p></div><button className="button" disabled={!!busy} onClick={()=>rsvp(event.id)}>{state.rsvps.some(r=>r.event_id===event.id)?'Remove RSVP':'Count me in'}</button></article>)}</div>}</section>
<section className="expeditions section" id="expeditions"><div className="next-heading"><h2>What’s next.</h2><p>Help choose our first outing. Dates and locations to come.</p></div><ExpeditionConsole selected={selected} onSelect={setSelected} onOpenNotes={()=>open('trip')} onVote={()=>vote(trip.id)} voted={!!state?.myVotes.some(v=>v.adventure_id===trip.id)} busy={!!busy} voteCount={state?.votes.find(v=>v.adventure_id===trip.id)?.count??0}/></section>
<section className="board section" id="board"><div className="idea-strip"><div><h2>Have an idea?</h2><p>A trail, a cleanup, something new. We’re listening.</p></div><button className="text-button" onClick={()=>open('idea')}>Suggest it <Plus size={18}/></button></div>{(error||loadError)&&!modal&&<div className="error" role="alert">{error||loadError} <button disabled={loading} onClick={retryBasecamp}>{loading?'Connecting…':'Retry'}</button></div>}{!!state?.proposals.length&&<details className="saved-ideas"><summary>Your saved ideas ({state.proposals.length})</summary><div>{state.proposals.map(p=><article key={p.id}><strong>{p.title}</strong><p>{p.description}</p></article>)}</div></details>}</section>
<section id="club" className="club-notes section"><details><summary>What SUMMIT stands for <Plus size={17}/></summary><div className="club-notes-content"><p>Explore. Serve. Lead. We get outside, give back, and grow by making things happen together.</p><dl>{values.map(v=><div key={v[1]}><dt><span>{v[0]}</span>{v[1]}</dt><dd>{v[2]}</dd></div>)}</dl><h3>The PEAK mindset</h3><dl>{peaks.map(p=><div key={p[0]}><dt><span>{p[0]}</span>{p[1]}</dt><dd>{p[2]}</dd></div>)}</dl></div></details></section></main>
<LeaderDesk open={leaderOpen} onOpenChange={setLeaderOpen} onChanged={retryBasecamp}/><footer><a className="wordmark" href="#home"><Mountain/><b>SUMMIT</b></a><span>EXPLORE. SERVE. LEAD.</span>{state?.leader&&<button className="text-button" onClick={()=>setLeaderOpen(true)}>Leadership desk</button>}<p>Cathedral Catholic High School<br/><small>Student club proposal</small></p></footer>
{notice&&<div className="toast" role="status"><CheckCircle2 size={20}/>{notice}</div>}
<Dialog open={modal!==null} onOpenChange={v=>{if(!v)setModal(null)}}><DialogContent className="summit-dialog"><DialogTitle className="dialog-title">{modal==='join'?(state?.member?'Your place at basecamp.':'Find your people.'):modal==='idea'?'Your idea starts here.':trip.name}</DialogTitle><DialogDescription>{modal==='join'?'SUMMIT · Cathedral Catholic High School':modal==='idea'?'Pitch an adventure or service idea to club leadership.':'Proposed experience · final details to be confirmed.'}</DialogDescription>
{modal==='join'&&(!state?connectionPrompt:!state.signedIn?<div className="auth-prompt"><Users size={45}/><p>Sign in to save your club interest, vote on adventures, and keep your ideas together.</p><a className="button" href="/signin-with-chatgpt?return_to=/%23basecamp" target="_top">Sign in with ChatGPT</a><p className="fine">Have a question? Connect with Tobias Kell at Cathedral Catholic.</p></div>:state.member?<><SummitPass member={state.member}/><p>Your interest is saved to the club database. Meeting and outing details are still being planned. This pass is not an event reservation or permission slip.</p><button className="button" onClick={()=>{setModal(null);document.querySelector('#expeditions')?.scrollIntoView({behavior:'smooth'})}}>Vote on our next adventure</button></>:<form onSubmit={join} className="club-form"><label>Your name<input name="name" autoComplete="name" required minLength={2} maxLength={70} placeholder="First and last name"/></label><div className="form-row"><label>Grade<Select value={grade} onValueChange={setGrade} required><SelectTrigger aria-label="Grade"><SelectValue placeholder="Choose grade"/></SelectTrigger><SelectContent>{['9','10','11','12'].map(g=><SelectItem value={g} key={g}>Grade {g}</SelectItem>)}</SelectContent></Select></label><label>I’m here for<Select value={interest} onValueChange={setInterest}><SelectTrigger aria-label="Interest"><SelectValue/></SelectTrigger><SelectContent>{['Explore','Serve','Lead','All of it'].map(g=><SelectItem value={g} key={g}>{g}</SelectItem>)}</SelectContent></Select></label></div><label className="check-label"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>I’m a Cathedral Catholic student and agree to save my name, grade, and interest for club registration.</span></label><p className="fine">Your details aren’t shown on the public board. Registering interest does not sign you up for an outing.</p><button className="button" disabled={!!busy||!consent||!grade}>{busy==='join'?'Saving your place…':'Join the crew'}</button></form>)}
{modal==='idea'&&(!state?connectionPrompt:!state.signedIn?<div className="auth-prompt"><p>Sign in so your idea stays saved to your basecamp.</p><a className="button" href="/signin-with-chatgpt?return_to=/%23board" target="_top">Sign in with ChatGPT</a></div>:<form className="club-form" onSubmit={propose}><label>Name your idea<input name="title" required minLength={5} maxLength={90} placeholder="What should we do?"/></label><label>Category<Select value={category} onValueChange={setCategory}><SelectTrigger aria-label="Idea category"><SelectValue/></SelectTrigger><SelectContent>{['Explore','Serve','Lead'].map(g=><SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select></label><label>The plan<textarea name="description" required minLength={15} maxLength={600} rows={4} placeholder="Where could we go? How could we help? What makes it a good club activity?"/></label><p className="fine">Saved to your basecamp and the leadership desk for review and planning.</p><button className="button" disabled={!!busy}>{busy==='idea'?'Saving…':'Save my idea'}</button></form>)}
{modal==='trip'&&<><p>{trip.description}</p><Tabs defaultValue="pack" className="trip-tabs"><TabsList><TabsTrigger value="pack">Pack list</TabsTrigger><TabsTrigger value="details">Before we go</TabsTrigger></TabsList><TabsContent value="pack"><p className="fine">Your checklist stays on this device. Adjust it once the outing is confirmed.</p><div className="pack-progress"><span>{trip.bring.filter(x=>packed.includes(x)).length}/{trip.bring.length} packed</span><div><i style={{width:`${trip.bring.filter(x=>packed.includes(x)).length/trip.bring.length*100}%`}}/></div></div>{trip.bring.map(item=><label className="pack-item" key={item}><Checkbox checked={packed.includes(item)} onCheckedChange={()=>pack(item)}/><span>{item}</span></label>)}</TabsContent><TabsContent value="details"><p>{trip.note}</p><p>Stay with your group, follow the trip leader’s directions, and check the confirmed event information before heading out.</p></TabsContent></Tabs><button className="button" onClick={downloadPlan}><Download size={17}/> Download field notes</button></>}
{error&&<p className="error" role="alert">{error}</p>}{loadError&&state&&modal!=='trip'&&<div className="error" role="alert">{loadError} <button disabled={loading} onClick={retryBasecamp}>{loading?'Connecting…':'Retry'}</button></div>}</DialogContent></Dialog></>;
}
