import { getChatGPTUser } from '../../chatgpt-auth';
import { database } from '../../../db/raw';
import { isLeader } from '../../../lib/leader';
import { adventures } from '../../../lib/adventures';
export const dynamic='force-dynamic';
function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}});}
export async function GET(){try{const user=await getChatGPTUser();const db=database();const totals=await db.prepare('SELECT adventure_id, COUNT(*) AS count FROM votes GROUP BY adventure_id').all();const member=user?await db.prepare('SELECT name, grade, interest, created_at FROM members WHERE user_id=?').bind(user.userId).first():null;const mine=user?await db.prepare('SELECT adventure_id FROM votes WHERE user_id=?').bind(user.userId).all():{results:[]};const ideas=user?await db.prepare('SELECT id, title, category, description, created_at FROM proposals WHERE user_id=? ORDER BY created_at DESC LIMIT 20').bind(user.userId).all():{results:[]};const events=await db.prepare("SELECT id,title,starts_at,location,details,status FROM events WHERE status='published' AND starts_at>? ORDER BY starts_at LIMIT 20").bind(new Date().toISOString()).all();const rsvps=user?await db.prepare('SELECT event_id FROM rsvps WHERE user_id=?').bind(user.userId).all():{results:[]};return json({signedIn:!!user,leader:isLeader(user),member,votes:totals.results,myVotes:mine.results,proposals:ideas.results,events:events.results,rsvps:rsvps.results});}catch(e){console.error('Basecamp read failed',e);return json({error:'Basecamp is temporarily unavailable. Please try again.'},503);}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin)return json({error:'Please submit from this website.'},403);if(!request.headers.get('content-type')?.includes('application/json'))return json({error:'JSON required'},415);const user=await getChatGPTUser();if(!user)return json({error:'Sign in to save your place at basecamp.'},401);const raw=await request.text();if(raw.length>5000)return json({error:'That submission is too long.'},413);let body;try{body=JSON.parse(raw)}catch{return json({error:'Invalid submission.'},400)}if(!body||typeof body!=='object'||Array.isArray(body))return json({error:'Invalid submission.'},400);const db=database();const now=new Date().toISOString();const clean=(v:unknown,min:number,max:number)=>typeof v==='string'&&v.trim().length>=min&&v.trim().length<=max;
if(body.action==='rsvp'){if(typeof body.eventId!=='string'||typeof body.selected!=='boolean')return json({error:'Choose a listed event.'},400);const event=await db.prepare("SELECT id FROM events WHERE id=? AND status='published' AND starts_at>?").bind(body.eventId,now).first();if(!event)return json({error:'This event is no longer available.'},409);const member=await db.prepare('SELECT user_id FROM members WHERE user_id=?').bind(user.userId).first();if(!member)return json({error:'Register your club interest before saving an RSVP.'},400);if(body.selected)await db.prepare('INSERT OR IGNORE INTO rsvps(user_id,event_id) VALUES(?,?)').bind(user.userId,body.eventId).run();else await db.prepare('DELETE FROM rsvps WHERE user_id=? AND event_id=?').bind(user.userId,body.eventId).run();return json({saved:true});}
if(body.action==='vote'){if(!adventures.some(a=>a.id===body.adventureId)||typeof body.selected!=='boolean')return json({error:'Choose a listed adventure.'},400);if(body.selected)await db.prepare('INSERT OR IGNORE INTO votes(user_id,adventure_id,created_at) VALUES(?,?,?)').bind(user.userId,body.adventureId,now).run();else await db.prepare('DELETE FROM votes WHERE user_id=? AND adventure_id=?').bind(user.userId,body.adventureId).run();return json({saved:true});}
if(body.action==='join'){if(!clean(body.name,2,70)||!['9','10','11','12'].includes(body.grade)||!['Explore','Serve','Lead','All of it'].includes(body.interest)||body.consent!==true)return json({error:'Complete your name, grade, interest, and consent.'},400);const member=await db.prepare('INSERT INTO members(user_id,name,grade,interest,created_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,grade=excluded.grade,interest=excluded.interest RETURNING name,grade,interest,created_at').bind(user.userId,body.name.trim(),body.grade,body.interest,now).first();return json({saved:true,member});}
if(body.action==='propose'){if(!clean(body.title,5,90)||!clean(body.description,15,600)||!['Explore','Serve','Lead'].includes(body.category)||!clean(body.requestId,36,36))return json({error:'Add a title, category, and 15–600 characters about your idea.'},400);const count=await db.prepare('SELECT COUNT(*) AS count FROM proposals WHERE user_id=?').bind(user.userId).first<{count:number}>();if((count?.count??0)>=20)return json({error:'You have 20 saved ideas. Share those with leadership before adding more.'},429);await db.prepare('INSERT OR IGNORE INTO proposals(id,user_id,title,category,description,created_at) VALUES(?,?,?,?,?,?)').bind(body.requestId,user.userId,body.title.trim(),body.category,body.description.trim(),now).run();return json({saved:true});}
return json({error:'Unknown action.'},400);}catch(e){console.error('Basecamp write failed',e);return json({error:'Could not save. Your input is still here; please try again.'},503);}}
